# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-10 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('Department', models.CharField(max_length=100)),
                ('Policy', models.CharField(max_length=500)),
                ('Policy_id', models.IntegerField(default=0)),
            ],
        ),
    ]
