# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-10 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gov',
            old_name='Policy_id',
            new_name='Policyid',
        ),
    ]
