# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-10 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gov', '0002_auto_20181010_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='gov',
            name='Policyname',
            field=models.CharField(default='0000000', max_length=1200),
        ),
    ]
