# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-10 09:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=120)),
                ('adhaar_no', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999)])),
                ('team_size', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('address', models.CharField(max_length=100)),
                ('proposal', models.CharField(max_length=500)),
            ],
        ),
    ]
