# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-11 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181011_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='user1',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
